version: '3.7'
services:
  # Application

  umbriel-api:
    image: umbriel-api
    container_name: umbriel-api
    restart: always
    ports:
      - ${APP_API_PORT}:${APP_API_PORT}
      - ${APP_API_PORT_WEEBHOOK}:${APP_API_PORT_WEEBHOOK}
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
