version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASS}
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - $HOME/docker-volumes/redis:/data
    networks:
      - umbriel-net

networks:
  umbriel-net:
    driver: bridge
